name: Post-Submit Continuous Integration
run-name: ${{ github.workflow }} in ${{ github.ref_name }}

on:
  schedule:
    - cron: "15 3 * * *"

defaults:
  run:
    shell: bash
    working-directory: voluncheer

jobs:
  format-lint-and-test:
    name: Post-Submit Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Locally
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Prepare Environment
        uses: ./.github/actions/prepare
      - name: Format and Lint Python
        uses: ./.github/actions/format
      - name: Test Python
        uses: ./.github/actions/test
