name: Continuous Integration
run-name: ${{ github.workflow }} run for ${{ github.actor }} in ${{ github.ref_name }}

on:
  push:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
  schedule:
    - cron: "15 2 * * *"

env:
  MINIMUM_COVERAGE: 70
  APP_NAME: "voluncheer"
  AWS_REGION: us-east-1

defaults:
  run:
    shell: bash
    working-directory: voluncheer

concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  format-lint-test:
    name: Checks format, lints, runs tests, and checks coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Locally
        uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare
      - name: Format and Lint Python
        uses: ./.github/actions/format
      - name: Test Python
        uses: ./.github/actions/test
      - name: Deploy to AWS
        # Only deploy when a PR on develop and/or main has been merged.
        if: ${{ success() && github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
        uses: ./.github/actions/deploy
        with:
          app-name: voluncheer
